stages:
- name: push
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn clean package fabric8:push  -Dcheckstyle.skip=true -Pkubernetes
        spring -f ./spring-cloud-kubernetes-examples/kubernetes-hello-world-example/pom.xml
timeout: 60
notification: {}
